In [2]:
import numpy as np

In [3]:
l2=[1,2,3,4]
np.array([3,4,5,6])+np.array(l2)

array([ 4,  6,  8, 10])

In [4]:
l1=[1,2,3,4]
np.array(l1)+2

array([3, 4, 5, 6])

In [5]:
m1=np.array([[1,2],[4,5],[6,7]])
m1

array([[1, 2],
       [4, 5],
       [6, 7]])

In [6]:
type(m1)

numpy.ndarray

In [8]:
m1.shape

(3, 2)

In [10]:
arr2=np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [12]:
m2=np.linspace(0,10,12)
m2

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [14]:
z=np.zeros(4)
z

array([0., 0., 0., 0.])

In [16]:
z1=np.zeros([4,3])
z1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
o1=np.ones([4,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
e=np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr1=np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr1_r1=arr1.reshape(10,2)
arr1_r1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [24]:
arr1_r1=arr1.reshape(5,4)
arr1_r1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
arr1_r1=arr1.reshape(4,5)
arr1_r1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])