In [67]:
import numpy as np
import matplotlib.pyplot as plt

In [68]:
x=np.arange(1,31)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [69]:
for i in range(1,len(x)//2+1):
    if(len(x)%i==0):
        y=x.reshape(len(x)//i,i)
        print(y)
        print(y.shape)
        print()

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(30, 1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]]
(15, 2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
(10, 3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
(6, 5)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
(3, 10)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]
(2, 15)



In [70]:
a=np.array([1,2,3,4])
np.exp(a)


array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [71]:
np.exp(1)

2.718281828459045

In [72]:
np.log(2)

0.6931471805599453

In [73]:
np.log10(4)

0.6020599913279624

In [74]:
np.log(10)

2.302585092994046

In [75]:
x=np.arange(1,6)
y=np.arange(3,8)

In [76]:
x,y

(array([1, 2, 3, 4, 5]), array([3, 4, 5, 6, 7]))

In [77]:
print("Add: ",x+y)
print("Sub: ",y-x)
print("Multiplication: ",x*y)
print("Division: ",x/y)
print("Power: ",x**y)
print("Inverse: ",1/x,1/y)

Add:  [ 4  6  8 10 12]
Sub:  [2 2 2 2 2]
Multiplication:  [ 3  8 15 24 35]
Division:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Power:  [    1    16   243  4096 78125]
Inverse:  [1.         0.5        0.33333333 0.25       0.2       ] [0.33333333 0.25       0.2        0.16666667 0.14285714]


In [78]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [79]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [80]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
y=np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
print("Add: \n",x+y)
print("Sub: \n",x-y)
print("Multiplication: \n",x*y)
print("Division: \n",y/x)

Add: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Sub: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[1.         0.         0.        ]
 [0.         0.2        0.        ]
 [0.         0.         0.11111111]]


In [83]:
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)
m1,m2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [84]:
print("Array multiplication: \n",m1@m2)

Array multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [85]:
m1=np.arange(1,17).reshape(4,4)
m2=np.arange(11,27).reshape(4,4)
m1,m2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26]]))

In [86]:
print("Array Multiplication:\n",m1@m2)

Array Multiplication:
 [[ 190  200  210  220]
 [ 462  488  514  540]
 [ 734  776  818  860]
 [1006 1064 1122 1180]]


In [87]:
np.linalg.multi_dot([m1,m2])

array([[ 190,  200,  210,  220],
       [ 462,  488,  514,  540],
       [ 734,  776,  818,  860],
       [1006, 1064, 1122, 1180]])

In [88]:
np.dot(m1,m2)

array([[ 190,  200,  210,  220],
       [ 462,  488,  514,  540],
       [ 734,  776,  818,  860],
       [1006, 1064, 1122, 1180]])

In [89]:
X=np.array([1,2,3,2,3,1,1,1,2]).reshape(3,3)
X

array([[1, 2, 3],
       [2, 3, 1],
       [1, 1, 2]])

In [90]:
Y=np.array([10,15,20]).reshape(3,1)
Y

array([[10],
       [15],
       [20]])

In [91]:
print(np.linalg.solve(X,Y))

[[ 26.25]
 [-13.75]
 [  3.75]]


In [92]:
t=np.transpose(X)
t

array([[1, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [93]:
X.T #transpose

array([[1, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [94]:
Z=X@t
Z

array([[14, 11,  9],
       [11, 14,  7],
       [ 9,  7,  6]])

In [95]:
print(np.max(Z))
print(np.min(Z))
print(np.sum(Z))

14
6
88


In [103]:
x=np.random.rand(10)
x

array([0.65405753, 0.96450662, 0.5964528 , 0.57465629, 0.33145793,
       0.74885231, 0.25811006, 0.35784333, 0.76987534, 0.68384716])

In [97]:
np.random.rand(5,5)

array([[0.81764334, 0.6416897 , 0.07916245, 0.10377347, 0.66448245],
       [0.70422297, 0.74736451, 0.481705  , 0.66120186, 0.84675027],
       [0.69047321, 0.20084931, 0.91804352, 0.09239904, 0.57251048],
       [0.12323395, 0.93461154, 0.41360768, 0.11659408, 0.03861375],
       [0.63430237, 0.12907122, 0.040298  , 0.54827529, 0.70578231]])

In [105]:
np.random.randn(2)

array([-0.02253759, -1.09980885])

In [106]:
x=np.random.randn(10,10)
x

array([[-1.18483416,  0.36562996, -0.30455346, -0.91449943, -1.38157744,
         0.74148633, -0.39418641,  0.47058342,  0.52024424,  0.76154993],
       [ 1.60214255, -0.15275578,  0.51082351, -0.19358678, -0.31039949,
         0.63063398,  0.6006579 , -0.42412231, -0.42965828, -0.43366656],
       [-0.41110725,  0.13394016, -1.0037664 , -0.73310201,  0.88271385,
         1.48292153,  1.21190364,  0.30040819, -0.53006665, -0.80420298],
       [ 0.92014164, -0.68432064, -0.61815667,  0.29824827, -1.57214202,
         0.48403465,  1.93124914, -0.82900336, -0.77794731, -1.0969069 ],
       [-0.45303951, -0.85260907, -0.79689673, -0.61409151,  0.8638529 ,
        -0.30729941,  0.82401635, -0.19929867,  1.823555  ,  0.31192719],
       [ 1.27342922,  0.97405073,  2.43571669,  0.41492195,  0.39137849,
         0.46609487, -0.34583023,  0.36943572, -0.91639084,  0.59649074],
       [-0.73304311, -0.4972809 , -0.25800982,  0.07869049,  1.18268784,
         0.1305766 , -0.57957624,  1.41342315

In [107]:
np.std(x)

0.8917256931220842

In [108]:
np.mean(x)

0.10306156947436948

In [112]:
#np.random.randint(low,high,size)
rn=np.random.randint(1,10,4)
rn

array([7, 8, 9, 9])

In [113]:
rn=np.random.randint(1,10,[3,3])
rn

array([[3, 1, 7],
       [4, 3, 2],
       [9, 3, 5]])